
services:

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lat
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
    - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "5051:80"
    depends_on:
      - mariadb


  lat:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      RUN_MODE: PRODUCTION
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
