package de.fherfurt.lat.storage.data.core;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.Date;

/**
 * Abstract base class for database entities.
 * <p>
 * This class provides common fields and methods for entities that are mapped to
 * database tables. It includes an auto-generated identifier and timestamps for
 * creation and last modification. The class uses JPA annotations for entity mapping
 * and lifecycle callbacks.
 * </p>
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
public abstract class AbstractDatabaseEntity {

    /**
     * The unique identifier for the entity.
     * <p>
     * This field is auto-generated by the database using the table strategy.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.TABLE)
    protected int id;

    /**
     * The timestamp of when the entity was created.
     * <p>
     * This field is set automatically before the entity is persisted to the database.
     * </p>
     */
    @Temporal(TemporalType.TIMESTAMP)
    protected Date created;

    /**
     * The timestamp of when the entity was last modified.
     * <p>
     * This field is updated automatically before the entity is updated in the database.
     * </p>
     */
    @Temporal(TemporalType.TIMESTAMP)
    protected Date modified;

    /**
     * Callback method that is invoked before the entity is persisted to the database.
     * <p>
     * This method sets the {@link #created} and {@link #modified} fields to the current date and time.
     * </p>
     */
    @PrePersist
    public void onCreate() {
        this.created = new Date();
        this.modified = new Date();
    }

    /**
     * Callback method that is invoked before the entity is updated in the database.
     * <p>
     * This method updates the {@link #modified} field to the current date and time.
     * </p>
     */
    @PreUpdate
    public void onUpdate() {
        this.modified = new Date();
    }
}